name: AdvancedRace
version: 1.0.0
description: 발전과제 데스런 플러그인
author: Admin
main: com.advancedrace.plugin.AdvancedRace
api-version: 1.13

commands:
  스트리머:
    description: 스트리머(팀장) 등록
    usage: /스트리머 <닉네임> [색깔]
    permission: advancedrace.command.streamer
  팀선택:
    description: 팀 선택 GUI 열기
    usage: ""
    permission: advancedrace.command.teamselect
  시작:
    description: 게임 시작
    usage: /시작
    permission: advancedrace.command.start
  종료:
    description: 게임 종료
    usage: /종료
    permission: advancedrace.command.end

permissions:
  advancedrace.command.streamer:
    description: 스트리머 명령어 사용
    default: op
  advancedrace.command.teamselect:
    description: 팀선택 명령어 사용
    default: true
  advancedrace.command.start:
    description: 게임 시작 명령어 사용
    default: op
  advancedrace.command.end:
    description: 게임 종료 명령어 사용
    default: op
