name: AdvancedRace
version: 1.0.0
description: 발전과제 데스런 플러그인
author: Admin
main: com.advancedrace.plugin.AdvancedRace

commands:
  스트리머:
    description: 스트리머(팀장) 등록
    usage: /스트리머 <닉네임>
  팀선택:
    description: 팀 선택 GUI 열기
    usage: /팀선택
  발전과제_tp:
    description: 신호기 위치로 텔레포트
    usage: /발전과제_tp <스트리머이름>

permissions:
  advancedrace.command.streamer:
    description: 스트리머 명령어 사용
    default: op
  advancedrace.command.teamselect:
    description: 팀선택 명령어 사용
    default: true
